const $=id=>document.getElementById(id);
const M=new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0});
const M2=new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:2});
const R=new Intl.NumberFormat('it-IT',{maximumFractionDigits:1});
let P={},EV=[],IC=[],T={};
async function j(p){const r=await fetch(p+'?v='+Date.now());if(!r.ok)throw Error(p);return r.json()}
function n(id){return +$(id).value||0}
function clamp(x,a,b){return Math.max(a,Math.min(b,x))}
function fuelKey(f){return f==='diesel'?'gasolio':f}
function unit(f){return f==='metano'?'kg':'l'}
function fp(f){const k=fuelKey(f),fuel=P.fuel||{};return fuel[k]||({benzina:1.82,diesel:1.7,gpl:.73,metano:1.45}[f]||1.82)}
function uniq(a){return [...new Set(a.filter(Boolean))].sort()}
function options(a,v='all',t='Tutti'){return '<option value="'+v+'">'+t+'</option>'+a.map(x=>'<option value="'+x+'">'+x+'</option>').join('')}
function checked(id){return !!$(id)?.checked}
function setLock(inputId,checkId){const el=$(inputId),on=checked(checkId);if(!el)return;el.readOnly=!on;if(el.tagName==='SELECT')el.disabled=!on;el.classList.toggle('readonly',!on)}
function allLocks(){[['publicChargePrice','overridePublicCharge'],['iceType','overrideFuel'],['iceConsumption','overrideConsumption'],['icePurchase','overridePurchase'],['evMaintenance','overrideEvMaintenance'],['iceMaintenance','overrideIceMaintenance'],['iceTax','overrideIceTax'],['evTaxAfter5','overrideEvTax']].forEach(x=>setLock(x[0],x[1]))}
function ev(){return EV.find(c=>c.id===$('evSelect').value)||EV[0]}
function ic(){return IC.find(c=>c.id===$('iceSelect').value)||IC[0]}
function iceCons(c){return c?.consumption_kg_100km||c?.consumption_l_100km||n('iceConsumption')}
function publicKwh(){return n('publicChargePrice')||T.market_average?.public_mixed||.74}
function blendedKwh(){const h=n('homeShare')/100,s=n('solarShare')/100;return h*(n('homePrice')*(1-s)+n('solarPrice')*s)+(1-h)*publicKwh()}
function powerKw(c){if(c?.power_kw)return +c.power_kw;const p=c?.price_eur||30000;if(c?.fuel==='diesel')return p>45000?140:p>32000?110:85;if(c?.fuel==='gpl'||c?.fuel==='metano')return 74;return p>45000?130:p>30000?100:75}
function iceTax(c){const kw=powerKw(c);return Math.round(kw<=100?kw*2.58:100*2.58+(kw-100)*3.87)}
function iceMaint(c){let b=(c?.price_eur||30000)*.018;if(c?.fuel==='diesel')b+=100;if(c?.fuel==='gpl'||c?.fuel==='metano')b+=80;return Math.round(clamp(b,350,1300)/10)*10}
function evMaint(c){return Math.round(clamp((c?.price_eur||35000)*.006,180,550)/10)*10}
function evTax(c){return Math.round(clamp(((c?.power_kw||90)*2.58)*.25,45,160)/5)*5}
function evFiltered(){const b=$('evBrandPick').value;return EV.filter(c=>b==='all'||c.brand===b)}
function iceFiltered(){const f=$('iceFuelPick').value,b=$('iceBrandPick').value;return IC.filter(c=>(f==='all'||c.fuel===f)&&(b==='all'||c.brand===b))}
function fillEv(){const cur=$('evSelect').value,arr=evFiltered();$('evSelect').innerHTML=arr.map(c=>'<option value="'+c.id+'">'+c.brand+' '+c.model+' - '+M.format(c.price_eur)+'</option>').join('');if(arr.some(c=>c.id===cur))$('evSelect').value=cur;else if(arr[0])$('evSelect').value=arr[0].id;$('evChoiceHint').textContent=arr.length+' elettriche filtrate';setAuto();calc()}
function fillIce(){const cur=$('iceSelect').value,arr=iceFiltered();$('iceSelect').innerHTML=arr.map(c=>'<option value="'+c.id+'">'+c.brand+' '+c.model+' '+(c.year||'')+' - da '+M.format(c.price_eur)+'</option>').join('');if(arr.some(c=>c.id===cur))$('iceSelect').value=cur;else if(arr[0])$('iceSelect').value=arr[0].id;$('iceChoiceHint').textContent=arr.length+' termiche filtrate';setAuto();calc()}
function setAuto(){const e=ev(),i=ic();if(!e||!i)return;const m=T.market_average||{};if(!checked('overridePublicCharge'))$('publicChargePrice').value=(e.brand==='Tesla'?(m.tesla_supercharger_owner||.50):(m.public_mixed||.74)).toFixed(2);if(!checked('overrideFuel'))$('iceType').value=i.fuel;if(!checked('overrideConsumption'))$('iceConsumption').value=iceCons(i);if(!checked('overridePurchase'))$('icePurchase').value=i.price_eur||30000;if(!checked('overrideEvMaintenance'))$('evMaintenance').value=evMaint(e);if(!checked('overrideIceMaintenance'))$('iceMaintenance').value=iceMaint(i);if(!checked('overrideIceTax'))$('iceTax').value=iceTax(i);if(!checked('overrideEvTax'))$('evTaxAfter5').value=evTax(e);allLocks();meta()}
function meta(){const e=ev(),i=ic();if(e)$('evMeta').innerHTML='<b>Dati EV</b><br>Anno: '+(e.year||2026)+' · Motorizzazione: '+(e.powertrain||e.motor||'elettrica')+' · Prezzo: '+M.format(e.price_eur)+'<br><small>'+(e.price_source||e.price_note||'Prezzo indicativo da verificare con configuratore/listino ufficiale')+'</small>';if(i)$('iceMeta').innerHTML='<b>Dati termica</b><br>Anno: '+(i.year||'-')+' · Motorizzazione: '+(i.powertrain||i.engine||i.model)+' · Potenza: '+(i.power_kw?i.power_kw+' kW':'stimata')+' · Prezzo: '+M.format(i.price_eur)+'<br><small>'+(i.price_source||i.price_note||'Prezzo indicativo da verificare con configuratore/listino ufficiale')+'</small>'}
function calc(){const e=ev(),i=ic();if(!e||!i)return;setAuto();const y=n('years'),km=n('annualKm')*y,e100=e.consumption_kwh_100km*blendedKwh()/(T.charging_efficiency?.mixed||.9),i100=n('iceConsumption')*fp($('iceType').value),et=e.price_eur+km/100*e100+y*n('evMaintenance')+Math.max(0,y-5)*n('evTaxAfter5'),it=n('icePurchase')+km/100*i100+y*n('iceMaintenance')+y*n('iceTax'),sav=it-et,yr=n('annualKm')/100*(i100-e100)+n('iceMaintenance')-n('evMaintenance')+n('iceTax'),diff=e.price_eur-n('icePurchase');$('savingTotal').textContent=(sav>=0?'+':'-')+M.format(Math.abs(sav));$('heroSaving').textContent=$('savingTotal').textContent;$('heroSavingText').textContent=e.brand+' '+e.model+' vs '+i.brand+' '+i.model;$('evPer100').textContent=M2.format(e100);$('icePer100').textContent=M2.format(i100);$('breakEven').textContent=diff<=0?'subito':yr<=0?'mai':diff/yr>30?'>30 anni':R.format(diff/yr)+' anni';$('explainBox').innerHTML='<b>'+e.brand+' '+e.model+'</b> contro <b>'+i.brand+' '+i.model+'</b>. Colonnine: '+M2.format(publicKwh())+'/kWh '+(e.brand==='Tesla'?'(tariffa Tesla indicativa)':'')+'. Termica '+R.format(n('iceConsumption'))+' '+unit($('iceType').value)+'/100 km, carburante '+M2.format(fp($('iceType').value))+'/'+unit($('iceType').value)+'. Manutenzione e bollo stimati automaticamente e modificabili solo con override.';cards();draw()}
function cards(){$('priceGasoline').textContent=M2.format(fp('benzina'))+'/l';$('priceDiesel').textContent=M2.format(fp('diesel'))+'/l';$('priceGpl').textContent=M2.format(fp('gpl'))+'/l';$('priceMetano').textContent=M2.format(fp('metano'))+'/kg';$('priceHome').textContent=M2.format(n('homePrice'))+'/kWh';$('pricePublic').textContent=M2.format(publicKwh())+'/kWh'}
function draw(){const h=n('homePrice')||.3,ef=T.charging_efficiency?.home||.92,q=($('carSearch').value||'').toLowerCase();$('carsTable').innerHTML=EV.filter(c=>(c.brand+' '+c.model).toLowerCase().includes(q)).map(c=>'<tr><td><b>'+c.brand+' '+c.model+'</b></td><td>'+(c.year||2026)+'</td><td>'+(c.powertrain||c.motor||'elettrica')+'</td><td>'+M.format(c.price_eur)+'</td><td>'+R.format(c.consumption_kwh_100km)+' kWh</td><td>'+R.format(c.battery_kwh||0)+'</td><td>'+(c.range_wltp_km||'-')+'</td><td>'+M2.format(c.consumption_kwh_100km*h/ef)+'</td></tr>').join('');const iq=($('iceSearch').value||'').toLowerCase(),f=$('iceFuelFilter').value,b=$('iceBrandFilter').value,arr=IC.filter(c=>(f==='all'||c.fuel===f)&&(b==='all'||c.brand===b)&&(c.brand+' '+c.model+' '+(c.powertrain||'')).toLowerCase().includes(iq));$('iceTable').innerHTML=arr.map(c=>'<tr><td><button onclick="useIce(\''+c.id+'\')">Usa</button></td><td><b>'+c.brand+' '+c.model+'</b></td><td>'+(c.year||'-')+'</td><td>'+(c.powertrain||c.engine||'-')+'</td><td>'+c.fuel+'</td><td>'+(c.power_kw?c.power_kw+' kW':'-')+'</td><td>'+M.format(c.price_eur)+'</td><td>'+R.format(iceCons(c))+' '+unit(c.fuel)+'/100</td><td>'+M2.format(iceCons(c)*fp(c.fuel))+'</td></tr>').join('')}
function useIce(id){const c=IC.find(x=>x.id===id);if(!c)return;$('iceFuelPick').value=c.fuel;$('iceBrandPick').value=c.brand;fillIce();$('iceSelect').value=c.id;setAuto();location.hash='simulatore';calc()}window.useIce=useIce;
Promise.all([j('data/prices.json'),j('data/cars_ev.json'),j('data/cars_ev_2.json'),j('data/cars_ev_3.json'),j('data/cars_ev_4.json'),j('data/cars_ev_5.json'),j('data/cars_ev_6.json'),j('data/cars_ev_7.json'),j('data/charging.json'),j('data/ice_cars_seed.json')]).then(a=>{P=a[0];EV=[...a[1].cars,...a[2].cars,...a[3].cars,...a[4].cars,...a[5].cars,...a[6].cars,...a[7].cars];T=a[8];IC=a[9].cars;EV.sort((a,b)=>a.price_eur-b.price_eur);IC.sort((a,b)=>a.price_eur-b.price_eur);$('evBrandPick').innerHTML=options(uniq(EV.map(c=>c.brand)),'all','Tutte');$('iceBrandPick').innerHTML=options(uniq(IC.map(c=>c.brand)),'all','Tutte');$('iceBrandFilter').innerHTML=options(uniq(IC.map(c=>c.brand)),'all','Tutte marche');$('homePrice').value=P.electricity.home;$('updatedAt').textContent='Aggiornamento: '+(P.updated_at||'-')+' · '+(P.status||'-');$('evBrandPick').oninput=fillEv;['iceFuelPick','iceBrandPick'].forEach(id=>$(id).oninput=fillIce);['overridePublicCharge','overrideFuel','overrideConsumption','overridePurchase','overrideEvMaintenance','overrideIceMaintenance','overrideIceTax','overrideEvTax'].forEach(id=>$(id).oninput=()=>{allLocks();setAuto();calc()});$('evSelect').oninput=()=>{setAuto();calc()};$('iceSelect').oninput=()=>{setAuto();calc()};document.querySelectorAll('input,select').forEach(x=>{if(!['evBrandPick','evSelect','iceFuelPick','iceBrandPick','iceSelect','overridePublicCharge','overrideFuel','overrideConsumption','overridePurchase','overrideEvMaintenance','overrideIceMaintenance','overrideIceTax','overrideEvTax'].includes(x.id))x.oninput=calc});fillEv();fillIce()}).catch(e=>document.body.insertAdjacentHTML('afterbegin','<div style="background:#ffdede;color:#4a0000;padding:12px;text-align:center">Errore dati: '+e.message+'</div>'));
